(#20, #19) Load from filesystem.
NCIOCPL/r4r-loader pull request #21
Opened 2024-03-06 18:15 UTC by blairlearn

Closes #19 
Closes #20

2024-10-28 15:14 UTC, bryanpizzillo requested changes
We should not have a copy of r4r-content here. (The resources under integration-tests). This should be testable with the same 5 resources from unit tests.

2025-10-07 17:44 UTC, welshja commented
@bryanpizzillo @blairlearn - should this stay open or get closed?

2025-10-07 18:32 UTC, blairlearn commented
It should stay open until there's a decision what to do with the loader overall. (Retire R4R altogether? Redo the loader in Python? Keep the JS version?)

2026-07-30 15:32 UTC, blairlearn commented
Will not complete.

2026-07-30 15:32 UTC, closed without merging